"""Keep every page's shared pieces in sync.

Run after editing partials/header.html, partials/footer.html, style.css, script.js,
or any page's <title> / <meta name="description">:

    python3 build.py

What it does to each *.html page in this folder:
  - replaces <header class="site-header">…</header> with partials/header.html
  - replaces <footer class="site-footer">…</footer> with partials/footer.html
  - marks the current page's nav link with aria-current="page"
  - points style.css / script.js at a version string based on their contents,
    so browsers pick up changes without a manual cache-bust
  - writes the link-preview tags (Open Graph / Twitter) used when a page is shared
    on iMessage, Instagram, LinkedIn, etc., built from the page's <title> and
    <meta name="description">
"""
import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).parent
SITE_URL = "https://nyusff.com/"
SITE_NAME = "NYU Sports Film Festival"
SHARE_IMAGE = SITE_URL + "assets/share-image.jpg"


def file_version(name):
    return hashlib.md5((ROOT / name).read_bytes()).hexdigest()[:8]


def share_tags(page, page_html):
    title = re.search(r"<title>(.*?)</title>", page_html, re.S)
    desc = re.search(r'<meta name="description" content="([^"]*)">', page_html)
    if not (title and desc):
        return ""
    title = title.group(1).strip()
    # Share cards already show the site name, so drop the " - NYU Sports Film Festival" suffix
    share_title = re.sub(r"\s+-\s+NYU Sports Film Festival$", "", title)
    url = SITE_URL + ("" if page.name == "index.html" else page.name)
    tags = [
        f'<link rel="canonical" href="{url}">',
        '<meta name="theme-color" content="#57068c">',
        '<link rel="apple-touch-icon" href="assets/android-chrome-512x512.png">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{SITE_NAME}">',
        f'<meta property="og:title" content="{share_title}">',
        f'<meta property="og:description" content="{desc.group(1)}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:image" content="{SHARE_IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{SITE_NAME}">',
        '<meta name="twitter:card" content="summary_large_image">',
    ]
    body = "\n".join("    " + t for t in tags)
    return f"    <!-- share-meta (generated by build.py) -->\n{body}\n    <!-- /share-meta -->"


def main():
    header = (ROOT / "partials/header.html").read_text(encoding="utf-8").rstrip()
    footer = (ROOT / "partials/footer.html").read_text(encoding="utf-8").rstrip()
    css_v, js_v = file_version("style.css"), file_version("script.js")

    changed = 0
    for page in sorted(ROOT.glob("*.html")):
        page_html = page.read_text(encoding="utf-8")
        new = page_html

        page_header = header.replace(
            f'href="{page.name}"', f'href="{page.name}" aria-current="page"'
        )
        new = re.sub(r'[ \t]*<header class="site-header">.*?</header>',
                     lambda _: page_header, new, count=1, flags=re.S)
        new = re.sub(r'[ \t]*<footer class="site-footer">.*?</footer>',
                     lambda _: footer, new, count=1, flags=re.S)
        new = re.sub(r'href="style\.css(\?v=[^"]*)?"', f'href="style.css?v={css_v}"', new)
        new = re.sub(r'<script src="script\.js(\?v=[^"]*)?"( defer)?></script>',
                     f'<script src="script.js?v={js_v}" defer></script>', new)

        new = re.sub(r"\n[ \t]*<!-- share-meta .*?<!-- /share-meta -->", "", new, flags=re.S)
        tags = share_tags(page, new)
        if tags:
            new = re.sub(r'(<meta name="description" content="[^"]*">)',
                         lambda m: m.group(1) + "\n" + tags, new, count=1)

        if new != page_html:
            page.write_text(new, encoding="utf-8")
            changed += 1

    print(f"Synced {changed} page(s). style.css v={css_v}, script.js v={js_v}")


if __name__ == "__main__":
    main()
